version: '3.4'

services:
  ZRA:
    container_name: ZRA
    image: ZRA
    build:
      context: .
      dockerfile: ./Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      
    ports:
      - 9089:9089
